
spring:
  cloud:
    stream:
      bindings:

        input:
          # as per binder, where the input file is
          destination: input/input.txt
#          group: dpp-local

          # must match a binder alias
          binder: file
        output:
          # as per binder, where the target output file
          destination: target/output.txt
          # must match a binder alias
          binder: file
    binders:
      # this is just an alias assigned
      file:
        # this value must match the name set in spring.binders
        type: myFileBinder



logging:
  level:
    org.springframework.cloud.stream.messaging.DirectWithAttributesChannel: DEBUG